### ISSUE TITLE
Don't get email notifications about your own posts

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/forums.openusercss.org#22]
Isn't it a bit stupid to get notified about the activity you've made. Stop spaming me @DecentM  :stuck_out_tongue:

**Comment by DecentM** [comment]
If you go into your settings you can set up so that you don't watch your own posts. This way you should still get notifications for replies, but I haven't tested this extensively.  
You can also switch your digests to be sent out less frequently, so you'll be more likely to get notifications once there are replies.

**Comment by RaitaroH** [comment]
Very well. I will change the setting mentioned. 
![image](https://user-images.githubusercontent.com/19552720/44050863-ebfe54c4-9f40-11e8-894a-704bfaeb86c7.png)

**Comment by DecentM** [comment]
Awesome! I'll close the issue because I think this should solve the problem, but please reopen if it still occurs.
